[tool.poetry]
name = "renotize"
version = "1.0.2"
description = "A utility script for quickly and automatically notarizing Ren'Py applications for macOS."
authors = ["CobaltCore <cobaltcore@yandex.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/kobaltcore/renotize"
homepage = "https://github.com/kobaltcore/renotize"

[tool.poetry.scripts]
renotize = "renotize.renotize:cli"

[tool.poetry.dependencies]
python = "^3.5"
click = "^7.1.1"
pyyaml = "^5.3.1"
logzero = "^1.5.0"
tqdm = "^4.45.0"
arrow = "^0.15.5"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
pytest = "^5.1"
codecov = "^2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
